"""lalau

Revision ID: c6137d8543b1
Revises: 
Create Date: 2024-11-28 22:09:20.436311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6137d8543b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_produto', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('id_fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['tb_fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_produto')
    op.drop_table('tb_fornecedor')
    # ### end Alembic commands ###
